title: "My Blog"
date: 2018-11-11

title: My Blogs
author: Prateek Sawhney
email: Prateek.sawhney97@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My Blog Site.

# social links
twitter_username: sawhney_prateek
github_username:  prateeksawhney97

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
